$ErrorActionPreference = "Stop"

$python = "$env:USERPROFILE\.conda\envs\orbit\python.exe"
if (-not (Test-Path $python)) {
    throw "orbit conda environment not found. Expected: $python"
}

$env:OLLAMA_MODEL = "gemma3:4b"
$env:OLLAMA_NUM_GPU = "36"
$env:OLLAMA_NUM_CTX = "2048"
$env:OLLAMA_NUM_PREDICT = "192"
$env:OLLAMA_TIMEOUT = "150"
$env:OLLAMA_KEEP_ALIVE = "15m"
$env:OLLAMA_API_URL = "http://127.0.0.1:11434/api/chat"
$env:HOMEBOX_URL = "http://192.168.31.3:3100"
$env:ORBIT_SCAN_MODE = "auto"
$env:ORBIT_SEGMENT_MAX_SIZE = "960"
$env:ORBIT_SCALE_AI_ROTATE = "180"
$env:ORBIT_EXPOSURE_RETRY = "1"
$env:ORBIT_EXPOSURE_TARGET_MEAN = "54"
$env:ORBIT_EXPOSURE_HIGHLIGHT_P98 = "242"
$env:ORBIT_EXPOSURE_CLIP_RATIO = "0.012"
$env:ORBIT_AI_ENHANCE = "1"
$env:ORBIT_AI_COMPOSITE_VIEW = "0"
$env:ORBIT_AI_IMAGE_MAX_SIZE = "640"
$env:ORBIT_AI_IMAGE_JPEG_QUALITY = "80"
$env:ORBIT_EXPOSURE_ROI = "0"
$env:ORBIT_AUX_CAMERA_ENABLED = "1"
$env:ORBIT_AUX_CAMERA_INDEX = "0"
$env:ORBIT_AUX_CAMERA_BACKEND = "dshow"
$env:ORBIT_AUX_CAMERA_AUTO_EXPOSURE = "1"
$env:ORBIT_AUX_CAMERA_CENTER_CROP = "1"
$env:ORBIT_AUX_CAMERA_WARMUP_SECONDS = "1.2"
$env:ORBIT_AUX_RECAPTURE_ON_SELECTION = "0"
$env:ORBIT_WRITE_RFID = "1"
$env:SCALE_PORT = "COM9"
$env:SCALE_BAUD = "9600"
$env:PYTHONUNBUFFERED = "1"
$env:PYTHONIOENCODING = "utf-8"

Write-Host "Using gemma3:4b with Vulkan GPU offload: OLLAMA_NUM_GPU=36, OLLAMA_NUM_CTX=2048"
Write-Host "Default scan mode: auto. Start Ollama first with:"
Write-Host "  powershell -ExecutionPolicy Bypass -File .\start_ollama_vulkan.ps1 -Restart"

& $python (Join-Path $PSScriptRoot "main.py") run --mode auto --ollama-model gemma3:4b --ollama-num-gpu 36 --ollama-num-ctx 2048 --ollama-num-predict 192 --ollama-timeout 150 @args
